// Minifies the browser runtime (src/internal/browser.ts) into
// src/internal/runtime.ts, the string the server inlines into pages. The
// generated file records a hash of its source; a test fails when it is
// stale. Run after editing browser.ts: bun scripts/build-runtime.ts
import { createHash } from "node:crypto"
import { mkdtempSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { script } from "../src/internal/browser.ts"

const root = fileURLToPath(new URL("..", import.meta.url))
const source = createHash("sha256").update(script).digest("hex")
const dir = mkdtempSync(join(tmpdir(), "lsc-runtime-"))
try {
  const entry = join(dir, "runtime.js")
  writeFileSync(entry, script)
  const result = await Bun.build({ entrypoints: [entry], target: "browser", format: "iife", minify: true })
  if (!result.success) throw new Error(result.logs.map(String).join("\n"))
  const minified = (await result.outputs[0]!.text()).trim()
  writeFileSync(
    `${root}src/internal/runtime.ts`,
    `// Generated by scripts/build-runtime.ts from browser.ts. Do not edit.
/** sha256 of the browser.ts script this was built from. */
export const source = ${JSON.stringify(source)}
export const script: string = ${JSON.stringify(minified)}
`
  )
  console.log(`runtime: ${script.length} -> ${minified.length} bytes (${Bun.gzipSync(Buffer.from(minified)).length} gzipped)`)
} finally {
  rmSync(dir, { recursive: true, force: true })
}
