// Copies idiomorph's minified build into src/internal/idiomorph.ts as a
// string, so the browser runtime can inline it without any asset pipeline.
// Run after bumping the idiomorph devDependency: bun scripts/vendor-idiomorph.ts
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
const pkg = JSON.parse(readFileSync(`${root}node_modules/idiomorph/package.json`, "utf8")) as { version: string }
const source = readFileSync(`${root}node_modules/idiomorph/dist/idiomorph.min.js`, "utf8").trim()

writeFileSync(
  `${root}src/internal/idiomorph.ts`,
  `// Generated by scripts/vendor-idiomorph.ts. Do not edit.
// idiomorph ${pkg.version} - https://github.com/bigskysoftware/idiomorph
// Copyright (c) 2022 Big Sky Software. Licensed under the MIT License.
export const version = ${JSON.stringify(pkg.version)}
export const idiomorph: string = ${JSON.stringify(source)}
`
)
console.log(`vendored idiomorph ${pkg.version} (${source.length} bytes)`)
